apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: udpt
data:
  JWT_SECRET: change-me-in-production-use-long-random-string
  JWT_ALGORITHM: HS256
  REDIS_URL: redis://redis:6379/0
  CONTRACT_SERVICE_URL: http://contract-service:8001
  PRICING_SERVICE_URL: http://pricing-service:8002
  OPERATION_SERVICE_URL: http://operation-service:8003
  BILLING_SERVICE_URL: http://billing-service:8004
  WORKFLOW_SERVICE_URL: http://workflow-service:8005
  NOTIFICATION_SERVICE_URL: http://notification-service:8006
  AUDIT_SERVICE_URL: http://audit-service:8007
  ESIGN_SERVICE_URL: http://esign-service:8008
